language: python
python:
  - "3.7.0"
# command to install dependencies
services:
  - postgresql
install: 
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE sendit_db;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'columbus';" -U postgres
# command to run tests
script: 
  - pytest --cov=api -v
after_success:
  - coveralls